# @rdd13r 2026-08-21
# Bugs, bugs, BUGS ... fn bugs: https://github.com/gradle/gradle/issues/28227
systemProp.apple.awt.UIElement=true

kotlin.code.style=official
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

kobwebExportLayout=STATIC
kobwebBuildTarget=RELEASE

org.gradle.jvmargs=--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -Xmx4g -Dfile.encoding=UTF-8

# Thangs that be before all other thangs
versionOfToolchainsFoojayResolver=1.0.0
versionOfKtor=3.5.2

group=me.riddle.adventure.web
version=0.1.0

launchBrowserOnRun=false

org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.logging.level=lifecycle
org.gradle.configuration-cache=true
org.gradle.isolated-projects=false
org.gradle.warning.mode=none
org.gradle.logging.stacktrace=internal
