ktor:
  deployment:
    port: 48080
  application:
    modules:
      - me.riddle.adventure.web.service.module.HttpKt.configureHttp
      - me.riddle.adventure.web.service.module.MonitoringKt.configureMonitoring
      - me.riddle.adventure.web.service.module.SerializationKt.configureSerialization
      - me.riddle.adventure.web.service.module.WebsocketsKt.configureWebsockets
      - me.riddle.adventure.web.service.module.StatusPagesKt.configureStatusPages
      - me.riddle.adventure.web.service.module.RoutingKt.configureRouting
  development: true
